dependencies:
- name: ocp4-aus-cp5-bala
  version: 1.0.0-1
  repository:  http://artifactory.gsi-learning-ocp43-clus-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.eu-gb.containers.appdomain.cloud/artifactory/generic-local/gsi-cloudnative-squad