dependencies:
  - name: ocp4-aus-cp4
    version: 0.0.2
    repository: >-
      https://artifactory-tools.gsi-learning-ocp43-clus-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.eu-gb.containers.appdomain.cloud/artifactory/generic-local/dev-aus1/
